// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Fallback placeholder lets `prisma generate` complete during the build
    // step, where the real DATABASE_URL isn't available yet. The real one
    // (built from DB_* vars) is set at runtime in scripts/start.js.
    url: process.env.DATABASE_URL ?? "mysql://placeholder:placeholder@localhost:3306/placeholder",
  },
});